#ifndef ROWS
#define ROWS 10
#endif

#ifndef COLS
#define COLS 41
#endif

#ifndef PACMAN_DEFAULT_COORD_X
#define PACMAN_DEFAULT_COORD_X 0
#endif

#ifndef PACMAN_DEFAULT_COORD_Y
#define PACMAN_DEFAULT_COORD_Y 0
#endif

#ifndef SHADOW_DEFAULT_COORD_X
#define SHADOW_DEFAULT_COORD_X 9
#endif

#ifndef SHADOW_DEFAULT_COORD_Y
#define SHADOW_DEFAULT_COORD_Y 39
#endif

#ifndef SPEEDY_DEFAULT_COORD_X
#define SPEEDY_DEFAULT_COORD_X 0
#endif

#ifndef SPEEDY_DEFAULT_COORD_Y
#define SPEEDY_DEFAULT_COORD_Y 39
#endif